fix/13-complete-app-flow
zohaibwebdev/AI-Summurizer pull request #13
Opened 2024-05-15 11:09 UTC by zohaibwebdev

![image](https://github.com/zohaibwebdev/AI-Summurizer/assets/67370102/a991af3e-5f5c-4e9a-81a2-cbe7c306c866)

2024-05-15 14:43 UTC, awaisshahid965 requested changes

2024-05-15 14:43 UTC, awaisshahid965 commented on src/shared/components/custom-button/custom-button.types.ts
> +    buttonType?: 'submit' | 'reset' | 'button'
should need to remove this

2024-05-15 14:43 UTC, awaisshahid965 commented on src/shared/components/summary/summary-detail/summary-detail.component.tsx
> +            {loading ? (
we are not allowed to use ternary operator in jsx

2024-05-15 14:43 UTC, awaisshahid965 commented on src/shared/components/summary/summary-form/summary-form.component.tsx
> +        <form action="" className="relative">
such case can also be done without forms

2024-05-15 14:43 UTC, awaisshahid965 commented on src/shared/components/summary/summary-history/summary-history.component.tsx
> +const SummaryHistory: FC<HistoryProps> = ({ history }) => {
what does this summary means?

2024-05-15 14:43 UTC, awaisshahid965 commented on src/shared/components/summary/summary-history/summary-history.component.tsx
> +const SummaryHistory: FC<HistoryProps> = ({ history }) => {
where is the function that handles what happens when we click on history

2024-05-15 14:43 UTC, awaisshahid965 commented on src/shared/components/summary/summary-history/summary-history.component.tsx
> +const SummaryHistory: FC<HistoryProps> = ({ history }) => {
plus component name needs to be changed that implies what it is intended to do

2024-05-15 14:43 UTC, awaisshahid965 commented on src/shared/components/summary/summary-history/summary-history.component.tsx
> +        setCopy(url)
for this, create a ticket in backlog says "optimize history component"

2024-05-15 14:43 UTC, awaisshahid965 commented on src/shared/components/summary/summary.types.ts
> +    loading?: boolean
why every member is optional? fix this

2024-05-15 14:43 UTC, awaisshahid965 commented on src/shared/icons/tick.icon.tsx
> +const TickIcon = () => {
where is default width and height? or what i need to do if i have to change any of its dimension

2024-05-15 14:43 UTC, awaisshahid965 commented on src/shared/icons/loader.icon.tsx
> +const LoaderIcon = () => {
same issue as in TickIcon

2024-05-15 14:47 UTC, zohaibwebdev commented on src/shared/components/custom-button/custom-button.types.ts
> +    buttonType?: 'submit' | 'reset' | 'button'
removed

2024-05-15 14:48 UTC, zohaibwebdev commented on src/shared/components/summary/summary-form/summary-form.component.tsx
> +        <form action="" className="relative">
done

2024-05-18 09:31 UTC, merged

2024-05-19 13:55 UTC, zohaibwebdev commented
![image](https://github.com/zohaibwebdev/AI-Summurizer/assets/67370102/6fd0e052-810e-4bb2-b169-3ff649eb701a)