feat: navigation bar
zohaibwebdev/AI-Summurizer pull request #3
Opened 2024-05-07 10:22 UTC by zohaibwebdev

2024-05-07 11:10 UTC, awaisshahid965 requested changes
Need to fix

2024-05-07 19:59 UTC, awaisshahid965 requested changes
Push changes then request review

2024-05-08 06:50 UTC, awaisshahid965 commented on shared/types/icon.type.ts
> +    height: number
Change file names to .types.ts

2024-05-08 06:50 UTC, zohaibwebdev commented on shared/types/icon.type.ts
> +    height: number
ok

2024-05-08 06:55 UTC, awaisshahid965 commented on shared/icons/logo.icon.tsx
> +const LogoIcon: React.FC<IIconType> = ({ width = '90', height = '30' }) => {
if interface members are number, why their default values are in string?

2024-05-08 06:55 UTC, awaisshahid965 commented on shared/types/icon.type.ts
> +export interface IIconType {
I think 'I' is added for interface, and we add **type** for a type. I don't think this is behaving as both interface and type so choose name accordingly like **IIconProps** if iterrface or **IconProps** if type.

2024-05-08 06:55 UTC, awaisshahid965 commented on shared/icons/logo.icon.tsx
> +            width={+width}
This is not okay as width is already a number

2024-05-08 07:09 UTC, awaisshahid965 approved these changes

2024-05-08 09:43 UTC, awaisshahid965 approved these changes

2024-05-08 09:45 UTC, merged